# Generated by Django 4.1.10 on 2023-08-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_flaggeditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='division',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.division'),
            preserve_default=False,
        ),
    ]
