# Generated by Django 4.1.10 on 2023-08-15 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_audit_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_image',
            name='image_model',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.item_image'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('items', models.ManyToManyField(to='db.item')),
            ],
        ),
    ]
