# Generated by Django 4.1.10 on 2023-08-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_remove_item_image_image_model_item_image_itemtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemTags',
            new_name='ItemTag',
        ),
    ]
