# Generated by Django 4.1.10 on 2023-08-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_rename_itemtags_itemtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtag',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='db.itemtag'),
        ),
    ]
