# Generated by Django 4.1.10 on 2023-08-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_remove_itemtag_items_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
