# Generated by Django 4.1.10 on 2023-09-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_item_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cancelled',
            field=models.DateField(blank=True, null=True),
        ),
    ]
