# Generated by Django 4.1.10 on 2023-09-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_item_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
