# Generated by Django 4.1.10 on 2023-10-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_item_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
